### ISSUE TITLE
Comments broken..

### ISSUE THREAD

**Issue by dkhamsing** [Dimillian/SwiftHN#32]
Also number of votes, author.. I guess the issue is in [HackerSwifter](https://github.com/Dimillian/HackerSwifter)

Fixed?
- https://github.com/Dimillian/SwiftHN/commit/f33b23ff154ff04400bb3bfcde6ecde27ec1013f
- https://github.com/Dimillian/HackerSwifter/commit/fc96db19386522b0a4086578033c319bda3163b4

![image](https://cloud.githubusercontent.com/assets/4723115/5828769/2d1c548c-a0bd-11e4-8012-1150ecce093f.jpg)

**Comment by Dimillian** [comment]
Yeah, fixed. I'll submit the update to the App Store shortly
